### ISSUE TITLE
Release 0.2.0 on pypi contains the code from release 0.1.0

### ISSUE THREAD

**Issue by rudolfbyker** [heartbeat-sh/heartbeat.py#7]
Compare:

- https://files.pythonhosted.org/packages/9c/cc/dddd81de8478a32dfd9faa3702ab9a9af8e5585aa2caa17c25b5e875c27b/heartbeat-sh-0.2.0.tar.gz
- https://github.com/heartbeat-sh/heartbeat.py/archive/refs/tags/0.2.0.tar.gz

The 0.2.0 release on Pypi contains the code from release 0.1.0. On github, the release is correct. This means that installing heartbeat_sh via pip causes the previous release to be installed.

**Comment by arieroos** [comment]
The problem is actually with the tags. I never tagged the 0.2.0 PyPi release, so then I tagged the latest one 0.2.0 by mistake, but never released it to PyPi. Please use release 0.3.0 on PyPi. I'll tag it as such on here too.
